const tester_magic = require('./tester_magic.js');

const SwitchKit = {
    Tag: {},
    CallProcessingEvent: {},
    GenerateCallProcessingEvent_Event: {},
    ICBType: {},
    ActionICBSubType: {},
    DataICBSubType: {},
    ExtendedDataICBSubType: {},
    ISDN_Formatted_IE: {},
    ISDN_Raw_IE: {},
    Generic_PPL_TLV: {},
    NPDI_Universal_ICB_TLV: {},
    SS7Message: {},
    SS7NTTVariantMessage: {},
    OutpulsingSignalType: {},
    PPLComponentID: {},
    PPLEventRequest: {
        ISUP_L3P_CIC_ITU: {},
        ISDN_L3P_Call_Control: {},
        SIP_UA: {},
    },
    PPLEventIndication: {
        ISUP_L3P_CIC_ITU: {},
        ISDN_L3P_Call_Control: {},
        SIP_UA: {},
        MTP3_LSAC: {},
        MTP3_TSFC: {},
    },
    DS0StatusChangeChannelStatus: {},
    CollectDigitStringMode: {},
    SignalType: {},
    DSPServiceType: {},
    OutpulseDigitsStringFormat: {},
    OutpulseDigitsStringMode: {},
    OutpulseDigitsGenerateEventFlag: {},
    RecAnnConnectConfigurationFlag: {},
    RecAnnConnectEventFlag: {},
    ConnectTonePattern: {},
    AIB: {},
    ReleaseDataType: {},
    Status: {},
};

const magicObjects = [
    [SwitchKit.Tag, "Tag", [
        [10066, "DS0StatusChange"],
        [50006, "PingLLC"],
        [50007, "PingLLCAck"],
        [232, "RouteControl"],
        [10232, "RouteControlAck"],
        [50000, "InterAppMsg"],
        [50011, "InterAppMsgAck"],
        [50004, "UserTimer"],
        [50005, "UserTimerAck"],
        [50002, "TransferChanMsg"],
        [50020, "TransferChanMsgAck"],
        [44, "OutseizeControl"],
        [10044, "OutseizeControlAck"],
        [0, "Connect"],
        [10000, "ConnectAck"],
        [85, "RecAnnConnect"],
        [10085, "RecAnnConnectAck"],
        [47, "ConnectTonePattern"],
        [10047, "ConnectTonePatternAck"],
        [10055, "ChannelReleaseRequest"],
        [10073, "ChannelReleased"],
        [10105, "ChannelReleasedWithData"],
        [188, "CollectDigitString"],
        [10188, "CollectDigitStringAck"],
        [4, "ConnectOneWay"],
        [10004, "ConnectOneWayAck"],
        [80, "ConnectOneWayForced"],
        [10080, "ConnectOneWayForcedAck"],
        [23, "ConnectWait"],
        [10023, "ConnectWaitAck"],
        [5, "ConnectWithData"],
        [10005, "ConnectWithDataAck"],
        [3, "ConnectWithPad"],
        [10003, "ConnectWithPadAck"],
        [30, "DisconnectTonePattern"],
        [10030, "DisconnectTonePatternAck"],
        [186, "GenerateCallProcessingEvent"],
        [10186, "GenerateCallProcessingEventAck"],
        [10045, "RFSWithData"],
        [10064, "RequestForService"],
        [8, "ReleaseChannel"],
        [10008, "ReleaseChannelAck"],
        [191, "ParkChannel"],
        [10191, "ParkChannelAck"],
        [32, "OutpulseDigits"],
        [10032, "OutpulseDigitsAck"],
        [86, "RecAnnDisconnect"],
        [10086, "RecAnnDisconnectAck"],
        [68, "PPLEventRequest"],
        [10068, "PPLEventRequestAck"],
        [90, "TransmitToneQuery"],
        [10090, "TransmitToneQueryAck"],
        [190, "DSPServiceCancel"],
        [10190, "DSPServiceCancelAck"],
        [189, "DSPServiceRequest"],
        [10189, "DSPServiceRequestAck"],
        [54, "ReleaseWithData"],
        [10054, "ReleaseWithDataAck"],
        [10046, "CallProcessingEvent"],
        [10067, "PPLEventIndication"],
        [50001, "RequestChannelAck"],
        [50029, "ConnectionStatusMsg"],
    ]],
    [SwitchKit.CallProcessingEvent, "CallProcessingEvent", [
        [0x0, "No_Event"],
        [0x1, "ANI_Request_Off_Hook"],
        [0x2, "Digits"],
        [0x3, "Wink_1"],
        [0x4, "Wink_2"],
        [0x5, "Wink_3"],
        [0x6, "Wink_4"],
        [0x7, "Wink_5"],
        [0x8, "Wink_6"],
        [0x9, "Wink_7"],
        [0xA, "Wink_8"],
        [0xB, "Dialtone_Detected"],
        [0xC, "Reserved"],
        [0xD, "Backward_R2_Signal"],
        [0xE, "First_Digit_Report"],
        [0xF, "PPL_Event"],
        [0x10, "Digit_With_Timing_Information"],
        [0x11, "Receive_Idle"],
        [0x13, "FAX_Tone_Detection"],
        [0x20, "Answer"],
        [0x21, "Tone_Complete"],
        [0x22, "Outpulsing_Complete"],
        [0x23, "Flash_Detected"],
        [0x24, "CPC_Detected"],
        [0x25, "Recorded_Announcement_Started"],
        [0x26, "Recorded_Announcement_Complete"],
        [0x27, "Timed_out_waiting_for_energy"],
        [0x28, "Energy_Result_Report"],
        [0x29, "Coin_Tone_Detection_Timeout"],
        [0x2A, "Coin_Tone_Detection_Report"],
        [0x2B, "Play_File_Started"],
        [0x2C, "Play_File_Complete"],
        [0x2D, "Record_File_Started"],
        [0x2E, "Record_File_Complete"],
        [0x2F, "File_Not_Found"],
        [0x30, "File_Play_Underrun"],
        [0x31, "File_Record_Overrun"],
        [0x32, "Record_Initial_Silence_Timeout"],
        [0x33, "Play_File_Queue_Failure"],
        [0x34, "Play_File_Stopped"],
        [0x35, "Record_File_Stopped"],
        [0x40, "DTMF_Subscription_Terminated"],
        [0x41, "DSP_Series_2_Fax_Processing_Events"],
        [0x42, "Truly_Silent_Channel_PVD_AMD"],
        [0x43, "Voice_Detect_Rising_Edge_PVD_AMD"],
        [0x44, "Voice_Detect_Falling_Edge_PVD_AMD"],
        [0x45, "Long_Term_Voice_Detect_Rising_Edge_PVD_AMD"],
        [0x46, "Long_Term_Voice_Detect_Falling_Edge_PVD_AMD"],
        [0x47, "Tone_Detect_Rising_Edge_PVD_AMD"],
        [0x48, "Tone_Detect_Falling_Edge_PVD_AMD"],
        [0x49, "Echo_Canceller_Event"],
        [0x50, "DSP_Series_2_FSK_Events"],
    ]],
    [SwitchKit.GenerateCallProcessingEvent_Event, "GenerateCallProcessingEvent_Event", [
        [0x1, "Answer_Call"],
        [0x2, "Flash"],
        [0x11, "Transmit_Offhook"],
        [0x12, "Transmit_Idle"],
    ]],
    [SwitchKit.ICBType, "ICBType", [
        [1, "Action"],
        [2, "Data"],
        [3, "ExtendedData"],
    ]],
    [SwitchKit.ActionICBSubType, "ActionICBSubType", [
        [0x0, "Null"],
        [0x1, "Scan_For_Wink_N"],
        [0x2, "Scan_For_ANI_Request_Off_hook"],
        [0x3, "Scan_For_Dial_Tone"],
        [0x4, "Report_Call_Processing_Event"],
        [0x5, "Outpulse_Stage_N_Address_Data"],
        [0x6, "Wait_For_Host_Address_Data"],
        [0x7, "Wait_For_Host_Control"],
        [0x8, "Send_Host_Acknowledgment"],
        [0x9, "Do_Call_Progress_Analysis"],
        [0xA, "Seize"],
        [0xB, "Use_Instruction_List"],
        [0xD, "Cancel_R2_Receiver"],
        [0xE, "Scan_For_Backward_R2_Signal"],
        [0xF, "Wait_For_Host_Control_With_Answer_Supervision"],
        [0x10, "Do_CPA_Without_Line_Signaling"],
        [0x11, "Delay_N_Milliseconds"],
    ]],
    [SwitchKit.DataICBSubType, "DataICBSubType", [
        [0x1, "Stage_N_Address_Data_Host_Supplied"],
        [0x2, "Stage_N_Address_Data_Previoulsy_Inpulsed"],
        [0x10, "ISDN_Formatted_IEs"],
        [0x11, "ISDN_Raw_IEs"],
        [0x12, "SS7_Parameters"],
        [0x15, "DASS2_DPNSS_Raw_Data"],
        [0x1C, "SS7_TUP_Formatted_Fields"],
        [0x1E, "Generic_PPL"],
        [0x25, "ISDN_Segmented_Message"],
    ]],
    [SwitchKit.ExtendedDataICBSubType, "ExtendedDataICBSubType", [
        [0x12, "SS7_Formatted_Parameters"],
        [0x1e, "Generic_PPL"],
        [0x20, "SS7_SCCP_Parameters"],
        [0x21, "SS7_TCAP_Parameters"],
        [0x28, "V5_Subscriber_ID"],
        [0x2B, "MTP3_User_Part_Parameter"],
        [0x2c, "V5_User_Port_Range"],
        [0x2d, "Q752_Parameter"],
        [0x2f, "V5_Statistics_Query"],
        [0x30, "V5_Statistics_Data"],
        [0x31, "V5_Status_Indication"],
        [0x33, "NPDI_Universal_ICB"],
        [0x34, "LAPD_Frame"],
        [0x35, "LAPD_Status"],
        [0x65, "TCAP_Primitive"],
    ]],
    [SwitchKit.ISDN_Formatted_IE, "ISDN_Formatted_IE", [
        [0x1, "Call_Reference"],
        [0x2, "Called_Party_Number", "sk_formatted_ie_called_party_number"],
        [0x3, "Calling_Party_Number", "sk_formatted_ie_calling_party_number"],
        [0x4, "Called_Party_Subaddress"],
        [0x5, "Calling_Party_Subaddress"],
        [0x6, "Redirecting_Number", "sk_formatted_ie_redirecting_number"],
        [0x7, "Cause", "sk_formatted_ie_cause"],
        [0x8, "Progress"],
        [0x9, "User_to_User"],
        [0xA, "Codeset_6"],
        [0xB, "Codeset_7"],
        [0x11, "Codeset_5"],
        [0x12, "Vari_A_Bill"],
    ]],
    [SwitchKit.Generic_PPL_TLV, "Generic_PPL_TLV", [
        [0x8, "Criteria_Type", "hexstring"],
        [0x9, "Terminating_Channel", "hexstring"],
        [0xF, "Router_Protocol_ID", "hexstring"],
        [0x13, "Routing_Method", "hexstring"],
        [0x39, "Associated_Span_Channel", "hexstring"],
        [0x65, "Physical_VoIP_Channel", "hexstring"],
        [0x71, "Virtual_VoIP_Channel", "hexstring"],
        [0x100, "RTP_Payload_Type", "hexstring"],
        [0x102, "RTP_Silence_Suppression", "hexstring"],
        [0x103, "RTP_Echo_Cancellation", "hexstring"],
        [0x104, "RTP_Packets_Lost", "hexstring"],
        [0x105, "RTP_Packets_Received", "hexstring"],
        [0x110, "RTP_Octets_Received", "hexstring"],
        [0x111, "RTP_Packets_Sent", "hexstring"],
        [0x112, "RTP_Octets_Sent", "hexstring"],
        [0x115, "Call_Agent_Mode", "hexstring"],
        [0x116, "Channel_Service_TLV", "hexstring"],
        [0x117, "Alerting_Propagation_Mode", "hexstring"],
        [0x118, "Companding_Conversion_Mode", "hexstring"],
        [0x119, "Media_Offer_Stage", "hexstring"],
        [0x11A, "Call_Agent_Mode_Physical_Channel_ID", "hexstring"],
        [0x1C2, "Minimum_Jitter_Buffer_Delay", "hexstring"],
        [0x1C3, "Maximum_Jitter_Buffer_Delay", "hexstring"],
        [0x1C4, "Adaptation_Rate", "hexstring"],
        [0x1C5, "Fax_Type_Enable", "hexstring"],
        [0x1C7, "Fax_Modem_Bypass_Coder_Type", "hexstring"],
        [0x1C8, "Protocol_Type", "hexstring"],
        [0x1D1, "RTP_Payload_Redundancy", "hexstring"],
        [0x1D2, "Fax_Payload_Redundancy", "hexstring"],
        [0x1D4, "Type_of_Service", "hexstring"],
        [0x1DF, "UDP_Source_Port_Validate", "hexstring"],
        [0x1E1, "Fax_Compatibility_Mode", "hexstring"],
        [0x1E2, "RFC_2833_Enable", "hexstring"],
        [0x1E6, "Source_T_38_Port", "hexstring"],
        [0x1E7, "Destination_T_38_Port", "hexstring"],
        [0x1E8, "Source_RTCP_Port", "hexstring"],
        [0x1E9, "Destination_RTCP_Port", "hexstring"],
        [0x1EB, "RTP_Timer_Timeout_VDAC_ONE", "hexstring"],
        [0x1EC, "Media_Inactivity_Detection_Timer", "hexstring"],
        [0x11, "Signaling_Route_Test_Control_Status", "hexstring"],
    ]],
    [SwitchKit.NPDI_Universal_ICB_TLV, "NPDI_Universal_ICB_TLV", [
        [0x2C1, "Vendor_ID", "hexstring"],
        [0x678, "Echo_Cancel_NLP_Threshold", "hexstring"],
        [0x2716, "Call_Identity__Interworking_Only", "hexstring"],
        [0x2717, "Called_Party_Number", "hexstring"],
        [0x2718, "Calling_Party_Number", "hexstring"],
        [0x271A, "Circuit_State__Interworking_Only", "hexstring"],
        [0x271B, "Cause_Indicators__Interworking_Only", "hexstring"],
        [0x2725, "Forward_Call_Indicators__Interworking_Only", "hexstring"],
        [0x2727, "Generic_Digit_Information__Interworking_Only", "hexstring"],
        [0x2729, "Generic_Number__Interworking_Only", "hexstring"],
        [0x272A, "Generic_Reference_Number__Interworking_Only", "hexstring"],
        [0x272B, "Hop_Counter__Interworking_Only", "hexstring"],
        [0x2737, "Original_Called_Number__Interworking_Only", "hexstring"],
        [0x273C, "Redirecting_Number__Interworking_Only", "hexstring"],
        [0x273D, "Redirection_Information__Interworking_Only", "hexstring"],
        [0x273E, "Redirection_Number__Interworking_Only", "hexstring"],
        [0x2745, "Transit_Network_Selection__Interworking_Only", "hexstring"],
        [0x2749, "Bearer_Capability__Interworking_Only", "hexstring"],
        [0x274E, "NPDI_Message_Type", "hexstring"],
        [0x274F, "Progress_Indicator__Interworking_Only", "hexstring"],
        [0x2750, "Display__Interworking_Only", "hexstring"],
        [0x2751, "High_Layer_Compatibility__Interworking_Only", "hexstring"],
        [0x2752, "Low_Layer_Compatibility__Interworking_Only", "hexstring"],
        [0x2753, "Calling_Party_Sub_Address__Interworking_Only", "hexstring"],
        [0x2754, "Called_Party_Sub_Address__Interworking_Only", "hexstring"],
        [0x2755, "Low_Layer_Compatibility_Layer_1_Info__Interworking_Only", "hexstring"],
        [0x2756, "Low_Layer_Compatibility_Layer_2_Information", "hexstring"],
        [0x2757, "Low_Layer_Compatibility_Layer_3_Information", "hexstring"],
        [0x2758, "Pulse_Notification__Interworking_Only", "hexstring"],
        [0x2759, "Call_State__Interworking_Only", "hexstring"],
        [0x275A, "Generic_Command__Interworking_Only", "hexstring"],
        [0x275B, "Generic_Command_Response__Interworking_Only", "hexstring"],
        [0x275C, "Signal__Interworking_Only", "hexstring"],
        [0x275D, "Pulsed_Signal__Interworking_Only", "hexstring"],
        [0x275F, "Recognition_Time__Interworking_Only", "hexstring"],
        [0x2760, "Line_Information__Interworking_Only", "hexstring"],
        [0x2761, "Channel_Identification", "hexstring"],
        [0x2762, "Date_and_Time__Interworking_Only", "hexstring"],
        [0x2763, "Carrier_Information__Interworking_Only", "hexstring"],
        [0x277D, "Universal_Message_Envelope__Interworking_Only", "hexstring"],
        [0x277E, "Remote_Side_Protocol", "hexstring"],
        [0x278C, "Connected_Number_Subaddress__Interworking_Only", "hexstring"],
        [0x278F, "Originating_Line_Information__Interworking_Only", "hexstring"],
        [0x2792, "Source_IP_Address", "ipv4_address"],
        [0x2793, "Source_RTP_Port", "uint32"],
        [0x2794, "Destination_IP_Address", "ipv4_address"],
        [0x2795, "Destination_RTP_Port", "uint32"],
        [0x27B0, "RTP_Payload_Type", "hexstring"],
        [0x27B1, "RTP_Payload_Size", "hexstring"],
        [0x27C1, "IP_Signaling_Series_3_Card_ID", "hexstring"],
        [0x27C2, "Remote_End_Signaling_IP_Address_Q_931", "ipv4_address"],
        [0x27C3, "Remote_End_Signaling_Port_Q_931", "hexstring"],
        [0x27C4, "Source_IP", "hexstring"],
        [0x27C5, "Source_Port", "hexstring"],
        [0x27C9, "Charge_Area_Information_Parameter", "hexstring"],
        [0x27CA, "Carrier_Information_Parameter__Interworking_Only", "hexstring"],
        [0x27CB, "Non_Presentation_Reason__Interworking_Only", "hexstring"],
        [0x27D0, "Partial_Calling_Line_Identity__Interworking_Only", "hexstring"],
        [0x27D8, "Source_H_323_ID", "hexstring"],
        [0x27D9, "Source_URL", "hexstring"],
        [0x27DA, "Source_E_mail", "hexstring"],
        [0x27DC, "Remote_H_323_ID", "hexstring"],
        [0x27DD, "Remote_URL", "hexstring"],
        [0x27DE, "Remote_E_mail", "hexstring"],
        [0x27E3, "Release_Cause_Code", "hexstring"],
        [0x290E, "NPDI_SIP_Proxy_IP_Address", "null_terminated_string"],
        [0x290F, "NPDI_SIP_Proxy_Port", "uint32"],
        [0x2910, "NPDI_SIP_Route_Type", "hexstring"],
        [0x2914, "NPDI_SIP_Local_Lookup", "hexstring"],
        [0x2915, "NPDI_SIP_Response_Code", "hexstring"],
        [0x2916, "SIP_A_Leg_Transport_Type", "hexstring"],
        [0x2917, "SIP_B_Leg_Transport_Type", "hexstring"],
        [0x2919, "NPDI_SIP_To_Username", "null_terminated_string"],
        [0x291A, "NPDI_SIP_To_Password", "null_terminated_string"],
        [0x291B, "NPDI_SIP_To_Hostname", "null_terminated_string"],
        [0x291C, "NPDI_SIP_To_Port", "uint32"],
        [0x291E, "NPDI_SIP_Refer_to_Username", "null_terminated_string"],
        [0x291F, "NPDI_SIP_Refer_to_Password", "null_terminated_string"],
        [0x2920, "NPDI_SIP_Refer_to_Hostname", "null_terminated_string"],
        [0x2921, "NPDI_SIP_Refer_to_Port", "uint32"],
        [0x2923, "NPDI_SIP_From_Username", "null_terminated_string"],
        [0x2924, "NPDI_SIP_From_Password", "null_terminated_string"],
        [0x2925, "NPDI_SIP_From_Hostname", "null_terminated_string"],
        [0x2926, "NPDI_SIP_From_Port", "uint32"],
        [0x2928, "NPDI_SIP_From_Display_Name", "null_terminated_string"],
        [0x292D, "NPDI_SIP_Contact_URI_Username", "null_terminated_string"],
        [0x292E, "NPDI_SIP_Contact_Password", "null_terminated_string"],
        [0x292F, "NPDI_SIP_Contact_Hostname", "null_terminated_string"],
        [0x2930, "NPDI_SIP_Contact_Port", "uint32"],
        [0x2931, "NPDI_SIP_Contact_Expires", "hexstring"],
        [0x2933, "SIP_Contact_Transport_Type", "hexstring"],
        [0x2934, "SIP_Contact_URI_User_Information_Qualifier", "null_terminated_string"],
        [0x2935, "SIP_Contact_URI_Parameters", "null_terminated_string"],
        [0x2936, "SIP_Tunnel_Type", "hexstring"],
        [0x2937, "NPDI_SIP_Authenticate_Scheme", "hexstring"],
        [0x2938, "NPDI_SIP_Authentication_Realm", "null_terminated_string"],
        [0x2939, "NPDI_SIP_Authenticate_Username", "null_terminated_string"],
        [0x293A, "NPDI_SIP_Authenticate_Password", "null_terminated_string"],
        [0x293B, "NPDI_SIP_Authorization_Username", "null_terminated_string"],
        [0x293C, "NPDI_SIP_Authorization_Password", "null_terminated_string"],
        [0x293D, "NPDI_SIP_Proxy_Authorization_Username", "null_terminated_string"],
        [0x293E, "NPDI_SIP_Proxy_Authorization_Password", "null_terminated_string"],
        [0x293F, "NPDI_SIP_Authentication_Timeout", "hexstring"],
        [0x2941, "SIP_Authorization_Header", "null_terminated_string"],
        [0x2942, "SIP_Proxy_Authorization_Header", "null_terminated_string"],
        [0x2943, "SIP_Authenticate_Header", "null_terminated_string"],
        [0x2944, "SIP_Proxy_Authenticate_Header", "null_terminated_string"],
        [0x294E, "SIP_Remote_IP_Address", "ipv4_address"],
        [0x294F, "SIP_Remote_IP_Port", "uint32"],
        [0x2950, "SIP_Call_ID", "null_terminated_string"],
        [0x2951, "SIP_From_Tag", "null_terminated_string"],
        [0x2952, "SIP_To_Tag", "null_terminated_string"],
        [0x2953, "Subsequent_Information_Status", "hexstring"],
        [0x2954, "SIP_Request_URI_Username", "null_terminated_string"],
        [0x2955, "SIP_Request_URI_Hostname", "null_terminated_string"],
        [0x2956, "SIP_Request_URI_Port", "uint32"],
        [0x2957, "SIP_Request_URI_User_Information_Qualifier", "null_terminated_string"],
        [0x2958, "SIP_Request_URI_Parameters", "null_terminated_string"],
        [0x2959, "SIP_Remote_Party_ID", "null_terminated_string"],
        [0x295A, "SIP_RPID_Privacy", "null_terminated_string"],
        [0x295B, "SIP_Subject_Header", "null_terminated_string"],
        [0x295C, "SIP_Message_Body", "null_terminated_string"],
        [0x295D, "Content_Type", "null_terminated_string"],
        [0x295E, "SIP_Hostname", "null_terminated_string"],
        [0x295F, "SIP_Port_Number", "uint32"],
        [0x2960, "Privacy_Header", "null_terminated_string"],
        [0x2961, "Private_Header_Container", "hexstring"],
        [0x2962, "Private_Header_Type", "hexstring"],
        [0x2963, "Private_Header_Data", "hexstring"],
        [0x29D4, "SIP_Do_Not_Close_Socket", "hexstring"],
        [0x29FF, "Media_Local_End_Point_Information", "hexstring"],
        [0x2A00, "Media_Remote_End_Point_Information", "hexstring"],
        [0x2A01, "Media_Per_Stream_Information", "hexstring"],
        [0x2A02, "Media_Per_Codec_Information", "hexstring"],
        [0x2A03, "Media_Type", "hexstring"],
        [0x2A07, "Media_Port", "hexstring"],
        [0x2A08, "Media_Payload_Type", "hexstring"],
        [0x2A09, "Media_Payload_Description", "hexstring"],
        [0x2A0A, "Media_Payload_Size", "hexstring"],
        [0x2A0B, "Media_Clock_Rate", "hexstring"],
        [0x2A0E, "Media_Connection_Address", "hexstring"],
        [0x2A13, "Media_Flow_Direction", "hexstring"],
    ]],
    [SwitchKit.SS7Message, "SS7Message", [
        [0x0, "IAM"],
        [0x1, "ACM"],
        [0x2, "ANM"],
        [0x3, "CON"],
        [0x4, "REL"],
        [0x5, "RLC"],
        [0x6, "CPG"],
        [0x7, "BLO"],
        [0x8, "BLA"],
        [0x9, "UBL"],
        [0xA, "UBA"],
        [0xB, "RSC"],
        [0xC, "CGB"],
        [0xD, "CGBA"],
        [0xE, "CGU"],
        [0xF, "CGUA"],
        [0x10, "GRS"],
        [0x11, "GRA"],
        [0x12, "CCR"],
        [0x13, "COT"],
        [0x14, "LPA"],
        [0x15, "CFN"],
        [0x16, "UCIC"],
        [0x17, "CQM"],
        [0x18, "CQR"],
        [0x19, "FAR"],
        [0x1A, "FAA"],
        [0x1B, "FRJ"],
        [0x1C, "USR"],
        [0x1D, "FAC"],
        [0x1E, "PAM"],
        [0x1F, "NRM"],
        [0x20, "CRG"],
        [0x21, "IDR"],
        [0x22, "IRS"],
        [0x23, "INR"],
        [0x24, "INF"],
        [0x25, "SUS"],
        [0x26, "RES"],
        [0x27, "SAM"],
        [0x28, "CVT"],
        [0x29, "CVR"],
        [0x2A, "CRM"],
        [0x2B, "CRA"],
        [0x2C, "UPT"],
        [0x2D, "UPA"],
        [0x2E, "EXM"],
        [0x4F, "MPM"],
        [0x50, "OPR"],
        [0x51, "CCL"],
        [0x52, "DRS"],
        [0x53, "FOT"],
        [0x54, "OLM"],
        [0x55, "SGM"],
        [0x56, "CMR"],
        [0x57, "CMC"],
        [0x58, "CMRJ"],
        [0x59, "LOP"],
        [0x5A, "APM"],
        [0x5B, "PRI"],
    ]],
    [SwitchKit.SS7NTTVariantMessage, "SS7NTTVariantMessage", [
        [0x20, "CHG"],
    ]],
    [SwitchKit.OutpulsingSignalType, "OutpulsingSignalType", [
        [1, "DTMF"],
        [2, "MFR1_host_does_not_include_KP_or_ST"],
        [3, "MFR2"],
        [4, "MFR1_host_includes_KP_and_any_ST"],
        [5, "Dial_Pulse"],
    ]],
    [SwitchKit.PPLComponentID, "PPLComponentID", [
        [0xF, "ISUP_L3P_CIC"],
        [0x5, "ISDN_L3P_Call_Control"],
        [0xA7, "SIP_UA"],
        [0x2E, "MTP3_LSAC"],
        [0x3F, "MTP3_TSFC"],
    ]],
    [SwitchKit.PPLEventRequest.ISUP_L3P_CIC_ITU, "PPLEventRequest.ISUP_L3P_CIC_ITU", [
        [0x1, "Send_ACM"],
        [0x2, "Send_CPG"],
        [0x3, "Send_ANM"],
        [0x4, "Send_BLO"],
        [0x5, "Send_CGB"],
        [0x6, "Send_UBL"],
        [0x7, "Send_CGU"],
        [0x8, "Send_GRS"],
        [0x9, "Send_RSC"],
        [0xA, "Send_HW_block"],
        [0xB, "Send_HW_unblock"],
        [0xC, "Indicate_CPC_to_wait_for_incoming_COT_report_when_the_continuity_check_is_being_performed_on_the_previous_circuit"],
        [0xD, "Send_incoming_continuity_check_report_when_the_continuity_check_was_performed_on_the_previous_circuit"],
        [0xE, "Send_unrecognized_message_to_the_network"],
        [0x1E, "Send_CON"],
        [0x1F, "Send_CQM"],
        [0x20, "Send_FAR"],
        [0x21, "Send_FAA"],
        [0x22, "Send_FRJ"],
        [0x23, "Send_USR"],
        [0x24, "Send_FAC"],
        [0x25, "Send_PAM"],
        [0x26, "Send_NRM"],
        [0x27, "Send_CRG"],
        [0x28, "Send_IDR"],
        [0x29, "Send_IRS"],
        [0x2A, "Send_INR"],
        [0x2B, "Send_INF"],
        [0x2D, "Send_SUS"],
        [0x2E, "Send_RES"],
        [0x32, "Send_SAM"],
        [0x33, "Reset_timer_T35"],
        [0x40, "Manual_Stop_For_Continuity_re_checking"],
        [0x41, "Send_CCR"],
        [0x42, "Send_UPT"],
        [0x43, "Send_CCL"],
        [0x44, "Send_OPR"],
        [0x46, "Send_FOT"],
        [0x47, "Send_DRS"],
        [0x49, "CMC_Request_with_without_Parameters"],
        [0x4A, "CMRJ_request_with_without_Parameters"],
        [0x4B, "CMR_Request_with_without_Parameters"],
        [0x4C, "Request_for_COT"],
        [0x4D, "Request_for_CCR"],
        [0x4E, "Request_for_LPA"],
        [0x55, "Loop_Prevention"],
        [0x60, "Send_SGM"],
    ]],
    [SwitchKit.PPLEventRequest.ISDN_L3P_Call_Control, "PPLEventRequest.ISDN_L3P_Call_Control", [
        [0x1, "ISDN_Alerting"],
        [0x2, "ISDN_Progress"],
        [0x3, "ISDN_Connect"],
        [0x4, "ISDN_Disconnect"],
        [0x6, "ISDN_User_Information"],
        [0x7, "ISDN_Facility"],
        [0xA, "ISDN_Register"],
        [0xC, "ISDN_Notify"],
        [0xD, "ISDN_Information"],
        [0x20, "ISDN_Vari_A_Bill"],
        [0x21, "ISDN_ANI_on_Demand"],
    ]],
    [SwitchKit.PPLEventRequest.SIP_UA, "PPLEventRequest.SIP_UA", [
        [0xA, "Accept_Registration_Request"],
        [0xB, "Reject_Registration_Request"],
        [0xC, "Authenticate_Request"],
        [0x10, "Query_All_Registration"],
        [0x11, "Query_Single_Registration"],
        [0x12, "Delete_All_PPL_Registrations"],
        [0x13, "Delete_Specific_Registration"],
        [0x1E, "Change_Local_Media_Connection_Attribute"],
        [0x1F, "Generate_Early_Media"],
        [0x20, "Notify"],
        [0x294B, "Notify_Status_which_contains_the_SIP_status_to_be_sent_to_the_UA_within_a_NOTIFY_message"],
        [0x23, "Subsequent_Data"],
        [0x29, "Do_Not_Close_Socket"],
    ]],
    [SwitchKit.PPLEventIndication.ISUP_L3P_CIC_ITU, "PPLEventIndication.ISUP_L3P_CIC_ITU", [
        [0x1, "Reset_circuit_success_indication"],
        [0x8, "Remote_maintenance_block_or_maintenance_group_block_indication"],
        [0x9, "Remote_maintenance_unblock_or_maintenance_group_unblock_indication"],
        [0xA, "ACM_received"],
        [0xB, "ANM_received"],
        [0xC, "CPG_received"],
        [0xE, "ISUP_protocol_violation"],
        [0xF, "Remote_hardware_group_block_indication"],
        [0x10, "Remote_hardware_group_unblock_indication"],
        [0x11, "CON_received"],
        [0x12, "Local_maintenance_block_or_group_maintenance_block_success"],
        [0x13, "Local_maintenance_unblock_or_group_maintenance_unblock_success"],
        [0x15, "Local_circuit_maintenance_unblocking_indication"],
        [0x16, "UCIC_received"],
        [0x19, "OLM_received"],
        [0x32, "SGM_message_received"],
        [0x5A, "SAM_wait_timer_expired"],
        [0x63, "DSP_Resource_Allocation_Failure"],
    ]],
    [SwitchKit.PPLEventIndication.ISDN_L3P_Call_Control, "PPLEventIndication.ISDN_L3P_Call_Control", [
        [0x1, "ISDN_Alerting"],
        [0x2, "ISDN_Progress"],
        [0x3, "ISDN_Connect"],
        [0x4, "ISDN_Disconnect"],
        [0x5, "ISDN_Release_Complete"],
        [0x6, "ISDN_User_Information"],
        [0x7, "ISDN_Facility"],
        [0x8, "ISDN_Facility_ACK"],
        [0x9, "ISDN_Facility_Reject"],
        [0xA, "ISDN_Register"],
        [0xC, "ISDN_Notify"],
        [0xD, "ISDN_Information"],
        [0x13, "More_Information_L3P_to_L3"],
        [0x14, "Call_Proceeding_Indication_L3P_to_L3"],
    ]],
    [SwitchKit.PPLEventIndication.SIP_UA, "PPLEventIndication.SIP_UA", [
        [0xA, "Incoming_Registration_Request"],
        [0xB, "Registration_Timer_Expired"],
        [0xC, "Incoming_De_registration_Request"],
        [0xD, "Registration_Query_Response"],
        [0x1E, "Media_Change_Detected"],
        [0x1F, "SIP_183_Progress"],
        [0x20, "Answer_on_B_Side_200_OK_response_with_a_Session_Description_Protocol"],
        [0x21, "Blind_Refer_PPL_Event_Indication"],
        [0x22, "Consultative_Refer_PPL_Event_Indication"],
        [0x23, "Subsequent_Data"],
        [0x24, "SIP_180_Ringing"],
    ]],
    [SwitchKit.PPLEventIndication.MTP3_LSAC, "PPLEventIndication.MTP3_LSAC", [
        [0x1, "Link_Activation_Failure"],
        [0x2, "Signaling_link_failure"],
        [0x3, "Signaling_link_test_failure"],
        [0x4, "Signaling_link_restoration"],
    ]],
    [SwitchKit.PPLEventIndication.MTP3_TSFC, "PPLEventIndication.MTP3_TSFC", [
        [0x1, "Destination_inaccessible"],
        [0x2, "Destination_accessible"],
        [0x15, "PAUSE_IND"],
        [0x16, "RESUME_IND"],
        [0x17, "STATUS_IND"],
    ]],
    [SwitchKit.DS0StatusChangeChannelStatus, "DS0StatusChangeChannelStatus", [
        [0, "Purge"],
        [1, "OutOfService"],
        [2, "InService"],
        [3, "Reserved"],
        [4, "Parked"],
        [5, "Blocked"],
        [6, "Unblocked"],
        [7, "OutOfService_Maintenance_Loopback"],
    ]],
    [SwitchKit.CollectDigitStringMode, "CollectDigitStringMode", [
        [0x1, "Fixed_Number_of_Digits"],
        [0x2, "Use_Terminating_Characters"],
        [0x3, "Use_KP_ST_Characters"],
        [0x4, "Use_Fixed_Number_of_Digits_or_Terminating_Characters"],
        [0x8, "Fixed_or_Indefinite_Number_of_Digits"],
    ]],
    [SwitchKit.SignalType, "SignalType", [
        [1, "DTMF"],
        [2, "MFR1"],
    ]],
    [SwitchKit.DSPServiceType, "DSPServiceType", [
        [0x1, "DTMF_Receiver"],
        [0x2, "Energy_Detection"],
        [0x3, "Call_Progress_Analysis_Receiver"],
        [0x4, "Coin_Tone_Receiver"],
        [0x81, "DTMF_Receiver__Matrix_Based_RFC_2833_collection"],
        [0xC1, "DTMF_Receiver__Matrix_Based_on_SUBSCRIBE_NOTIFY"],
        [0xE1, "DTMF_Receiver__with_Termination_of_Tone_Announcement"],
    ]],
    [SwitchKit.OutpulseDigitsStringFormat, "OutpulseDigitsStringFormat", [
        [0, "BCD"],
        [1, "Non_BCD"],
    ]],
    [SwitchKit.OutpulseDigitsStringMode, "OutpulseDigitsStringMode", [
        [0, "CSP_inserts_KP_ST_framing_digits"],
        [1, "Host_inserts_framing_digits"],
    ]],
    [SwitchKit.OutpulseDigitsGenerateEventFlag, "OutpulseDigitsGenerateEventFlag", [
        [0, "No_OutpulsingComplete_Event"],
        [1, "OutpulsingComplete_Event"],
    ]],
    [SwitchKit.RecAnnConnectConfigurationFlag, "RecAnnConnectConfigurationFlag", [
        [0, "No_Barge_In"],
        [1, "Barge_In"],
    ]],
    [SwitchKit.RecAnnConnectEventFlag, "RecAnnConnectEventFlag", [
        [0, "No_Events"],
        [1, "RecAnnCompleted"],
        [2, "RecAnnStarted"],
        [3, "RecAnnCompleted_RecAnnStarted"],
    ]],
    [SwitchKit.ConnectTonePattern, "ConnectTonePattern", [
        [0x1, "Dial_Tone"],
        [0x2, "Ringback"],
        [0x3, "Busy"],
        [0x4, "Reorder"],
        [0x5, "Warning"],
        [0x6, "Call_Waiting"],
        [0x7, "ONI_Call__Zip_Tone"],
        [0x8, "ANI_Failure__Zip_Tone"],
        [0x9, "Confirmation_Tone"],
        [0xA, "Recall_Dial_Tone"],
        [0xB, "Class_of_Service__Tone_2"],
        [0xC, "Class_of_Service__Tone_3"],
        [0xD, "Intercept"],
        [0xE, "Vacant_Code"],
        [0xF, "Reorder_LEC"],
        [0x10, "No_Circuit_LEC"],
        [0x11, "Reorder_Carrier"],
        [0x12, "No_Circuit_Carrier"],
        [0x13, "Three_second__400_Hz_Tone"],
        [0x14, "Specialized_tone_to_wait_500_ms_then_play_480Hz_for_800_ms"],
        [0x15, "Bong_Tone__Calling_Card_Service_Prompt_Tone"],
    ]],
    [SwitchKit.AIB, "AIB", [
        [0x0, "Null"],
        [0x1, "Slot"],
        [0x6, "ISDN_Call_Reference"],
        [0x8, "SS7_Stack"],
        [0x9, "SS7_Link"],
        [0xC, "Logical_Span"],
        [0xD, "Channel"],
        [0xE, "EXS_Host_Slave_Node"],
        [0x10, "Logical_Physical_Node"],
        [0x11, "Logical_Physical_Span"],
        [0x12, "DSP_SIMM"],
        [0x13, "Physical_Span"],
        [0x14, "SS7_CIC_Group"],
        [0x15, "ISDN_Primary_D_Channel"],
        [0x16, "ISDN_Secondary_D_Channel"],
        [0x17, "Subrate"],
        [0x1A, "EXNET_Ring"],
        [0x1C, "SS7_Destination_ID"],
        [0x1D, "SS7_Route"],
        [0x1E, "SS7_Link_Set"],
        [0x1F, "SS7_Link_Set_Link"],
        [0x20, "SS7_Destination_Route"],
        [0x21, "SS7_Slot"],
        [0x22, "DSP_Chip"],
        [0x23, "Slot_Subrate"],
        [0x25, "Subrate_Channel"],
        [0x27, "ISDN_BRI_TEI"],
        [0x29, "Router"],
        [0x2A, "SS7_Subsystem_Number"],
        [0x2C, "V5_ID"],
        [0x2D, "V5_ID_Link_ID"],
        [0x2F, "V5_Interface_ID__User_Port"],
        [0x30, "V5_Interface_ID__User_Port_Link_Timeslot"],
        [0x31, "SS7_Virtual_CIC"],
        [0x32, "DS3_Offset"],
        [0x36, "MCC"],
        [0x3A, "D_Channel_Data_Link_Connection_Identifier"],
        [0x3C, "Number_of_CICS"],
        [0x3D, "Ring_Configuration_Query"],
        [0x42, "VoIP_Module"],
        [0x45, "Child_Conference_ID"],
        [0x48, "Ring_Communication_Link"],
        [0x52, "IP_Signaling_Series_3_Card_ID_or_Expanded_Logical_Node_ID"],
        [0x53, "Object_Type"],
        [0x55, "Conference_ID"],
        [0x64, "Global_Object_Type"],
        [0x65, "Global_Object_ID"],
        [0x67, "Functional_Area"],
        [0x73, "IP_Signaling_Series_3_Card_ID"],
        [0x7F, "SIP_Stack_ID"],
    ]],
    [SwitchKit.ReleaseDataType, "ReleaseDataType", [
        [0x03, "ISDN_ICB_Formatted_IE_and_Raw_IE_or_DASS_2_DPNSS_Raw_IE_Data"],
        [0x04, "SS7_ICB"],
        [0x33, "NPDI_Universal_ICB"],
    ]],
    [SwitchKit.Status, "Status", [
        [16, "POSITIVE_ACK"],
        [-3, "SK_LOST_LLC"],
    ]],
];

magicObjects.forEach(([obj, path, items]) => {
    items.forEach(([id, name, format]) => {
        obj[name] = tester_magic.generate(id, name, `SwitchKit.${path}.${name}`, format || "");
        obj[id] = obj[name];
    });
});

function createProxy(obj, path = 'SwitchKit') {
    return new Proxy(obj, {
        get(target, prop) {
            if (prop in target) {
                const value = target[prop];
                if (typeof value === 'object' && value !== null && !value.__tester_magic__) {
                    return createProxy(value, `${path}.${String(prop)}`);
                }
                return value;
            } else {
                throw new Error(`${path}.${String(prop)} is invalid`);
            }
        }
    });
}

module.exports = createProxy(SwitchKit);
